/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dilkursu;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdurrahman_account
 */
public class Anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form Anasayfa
     */
    static ArrayList<Sube> sube;
    static ArrayList<Kurs> kurs;
    static ArrayList<Ogrenci> ogrenci;
    static ArrayList<acilanKurslar> acilanKurslar;

    public Anasayfa() {
        initComponents();

    }

    Anasayfa(String text) {
        initComponents();
        //Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        lbl_subeAdi1.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_odemeAl = new javax.swing.JDialog();
        cmb_ogrenciList = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        lbl_t1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbl_t2 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lbl_t3 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        lbl_t4 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lbl_t5 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        btn_odeKaydet1 = new javax.swing.JButton();
        frame_ogrenciKaydet = new javax.swing.JFrame();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_takvim = new javax.swing.JTable();
        cmb_subelistesi = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cmb_odemeTipi = new javax.swing.JComboBox<>();
        txt_isim = new javax.swing.JTextField();
        txt_soyisim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_subeNot = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cmb_derslist = new javax.swing.JComboBox<>();
        btn_odeKaydet = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        lbl_tutar = new javax.swing.JLabel();
        lbl_taksit1 = new javax.swing.JLabel();
        lbl_taksit2 = new javax.swing.JLabel();
        lbl_taksit3 = new javax.swing.JLabel();
        lbl_taksit4 = new javax.swing.JLabel();
        lbl_taksit5 = new javax.swing.JLabel();
        txt_taksit1 = new javax.swing.JTextField();
        txt_taksit2 = new javax.swing.JTextField();
        txt_taksit3 = new javax.swing.JTextField();
        txt_taksit4 = new javax.swing.JTextField();
        txt_taksit5 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        frame_dersProgramı = new javax.swing.JFrame();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_takvim1 = new javax.swing.JTable();
        cmb_subelistesi1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_subeAdi1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        frame_odemeAl.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                frame_odemeAlWindowDeactivated(evt);
            }
        });

        cmb_ogrenciList.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cmb_ogrenciList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ogrenciListİtemStateChanged(evt);
            }
        });
        cmb_ogrenciList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_ogrenciListMouseClicked(evt);
            }
        });
        cmb_ogrenciList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ogrenciListActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel36.setText("Öğrenci Listesi");

        lbl_t1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_t1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_t1.setText(" ");

        jLabel38.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel38.setText("1.Taksit");

        lbl_t2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_t2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_t2.setText(" ");

        jLabel45.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel45.setText("2.Taksit");

        lbl_t3.setBackground(new java.awt.Color(255, 255, 255));
        lbl_t3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_t3.setText(" ");

        jLabel47.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel47.setText("3.Taksit");

        lbl_t4.setBackground(new java.awt.Color(255, 255, 255));
        lbl_t4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_t4.setText(" ");

        jLabel49.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel49.setText("4.Taksit");

        lbl_t5.setBackground(new java.awt.Color(255, 255, 255));
        lbl_t5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_t5.setText(" ");

        jLabel51.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel51.setText("5.Taksit");

        btn_odeKaydet1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btn_odeKaydet1.setText("Ödeme Al");
        btn_odeKaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_odeKaydet1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_odemeAlLayout = new javax.swing.GroupLayout(frame_odemeAl.getContentPane());
        frame_odemeAl.getContentPane().setLayout(frame_odemeAlLayout);
        frame_odemeAlLayout.setHorizontalGroup(
            frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_odemeAlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_odemeAlLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_ogrenciList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(frame_odemeAlLayout.createSequentialGroup()
                        .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_t2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_t3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_t4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_t5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_odeKaydet1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        frame_odemeAlLayout.setVerticalGroup(
            frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_odemeAlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frame_odemeAlLayout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_t5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frame_odemeAlLayout.createSequentialGroup()
                        .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_ogrenciList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(33, 33, 33)
                        .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frame_odemeAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(frame_odemeAlLayout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_t1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(frame_odemeAlLayout.createSequentialGroup()
                                    .addComponent(jLabel45)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_t2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(frame_odemeAlLayout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_t3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frame_odemeAlLayout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_t4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(btn_odeKaydet1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel27.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel27.setText("Bir Lisan Bir İnsan Dil Kursu");

        jLabel28.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel28.setText("Şube Listesi :");

        tbl_takvim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:00 - 10:00", null, null, null, null, null},
                {"10:00 - 11:00", null, null, null, null, null},
                {"11:00 - 12:00", null, null, null, null, null},
                {"13:00 - 14:00", null, null, null, null, null},
                {"14:00 - 15:00", null, null, null, null, null},
                {"15:00 - 16:00", null, null, null, null, null},
                {"16:00 - 17:00", null, null, null, null, null}
            },
            new String [] {
                "Saatler", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_takvim.setColumnSelectionAllowed(true);
        tbl_takvim.setRowHeight(45);
        tbl_takvim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_takvimMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbl_takvim);
        tbl_takvim.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        cmb_subelistesi.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cmb_subelistesi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_subelistesiİtemStateChanged(evt);
            }
        });
        cmb_subelistesi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_subelistesiMouseClicked(evt);
            }
        });
        cmb_subelistesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_subelistesiActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel29.setText("İsim         :");

        jLabel30.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel30.setText("Soyisim      :");

        jLabel31.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel31.setText("Ödeme Tipi   :");

        cmb_odemeTipi.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cmb_odemeTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesin", "Taksit" }));
        cmb_odemeTipi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_odemeTipiİtemStateChanged(evt);
            }
        });
        cmb_odemeTipi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_odemeTipiMouseClicked(evt);
            }
        });
        cmb_odemeTipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_odemeTipiActionPerformed(evt);
            }
        });

        txt_soyisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soyisimActionPerformed(evt);
            }
        });

        txt_subeNot.setColumns(20);
        txt_subeNot.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txt_subeNot.setRows(5);
        jScrollPane1.setViewportView(txt_subeNot);

        jLabel32.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel32.setText("Şube Notları");

        jLabel33.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel33.setText("Dersler      :");

        cmb_derslist.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cmb_derslist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_derslistİtemStateChanged(evt);
            }
        });
        cmb_derslist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_derslistMouseClicked(evt);
            }
        });
        cmb_derslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_derslistActionPerformed(evt);
            }
        });

        btn_odeKaydet.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btn_odeKaydet.setText("KAYDET");
        btn_odeKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_odeKaydetActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel34.setText("Ücret        :");

        lbl_tutar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_tutar.setForeground(new java.awt.Color(255, 0, 51));
        lbl_tutar.setText(" ");

        lbl_taksit1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_taksit1.setText("Taksit 1      :");

        lbl_taksit2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_taksit2.setText("Taksit 2      :");

        lbl_taksit3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_taksit3.setText("Taksit 3      :");

        lbl_taksit4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_taksit4.setText("Taksit 4      :");

        lbl_taksit5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_taksit5.setText("Taksit 5      :");

        txt_taksit1.setText(" ");

        txt_taksit2.setText(" ");
        txt_taksit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_taksit2ActionPerformed(evt);
            }
        });

        txt_taksit3.setText(" ");

        txt_taksit4.setText(" ");

        txt_taksit5.setText(" ");

        jLabel40.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel40.setText("₺");

        jLabel41.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel41.setText("₺");

        jLabel42.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel42.setText("₺");

        jLabel43.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel43.setText("₺");

        jLabel44.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel44.setText("₺");

        javax.swing.GroupLayout frame_ogrenciKaydetLayout = new javax.swing.GroupLayout(frame_ogrenciKaydet.getContentPane());
        frame_ogrenciKaydet.getContentPane().setLayout(frame_ogrenciKaydetLayout);
        frame_ogrenciKaydetLayout.setHorizontalGroup(
            frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                        .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_odemeTipi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_isim, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_soyisim, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_derslist, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_ogrenciKaydetLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_subelistesi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_tutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(50, 50, 50)
                        .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_odeKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                        .addComponent(lbl_taksit1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_taksit1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel40))
                                    .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                        .addComponent(lbl_taksit2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_taksit2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel41))
                                    .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                        .addComponent(lbl_taksit3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_taksit3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel42))
                                    .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                        .addComponent(lbl_taksit4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_taksit4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel43))
                                    .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                        .addComponent(lbl_taksit5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_taksit5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel44)))))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        frame_ogrenciKaydetLayout.setVerticalGroup(
            frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_ogrenciKaydetLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txt_isim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(cmb_subelistesi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txt_soyisim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_derslist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(30, 30, 30)
                        .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(cmb_odemeTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(lbl_tutar)))
                    .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                        .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_taksit1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_taksit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frame_ogrenciKaydetLayout.createSequentialGroup()
                                .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_taksit2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_taksit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_taksit3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_taksit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_taksit4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_taksit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(frame_ogrenciKaydetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_taksit5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_taksit5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_odeKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jLabel35.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel35.setText("Bir Lisan Bir İnsan Dil Kursu");

        jLabel37.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel37.setText("Şube Listesi     :");

        tbl_takvim1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:00 - 10:00", null, null, null, null, null},
                {"10:00 - 11:00", null, null, null, null, null},
                {"11:00 - 12:00", null, null, null, null, null},
                {"13:00 - 14:00", null, null, null, null, null},
                {"14:00 - 15:00", null, null, null, null, null},
                {"15:00 - 16:00", null, null, null, null, null},
                {"16:00 - 17:00", null, null, null, null, null}
            },
            new String [] {
                "Saatler", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_takvim1.setColumnSelectionAllowed(true);
        tbl_takvim1.setRowHeight(45);
        tbl_takvim1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_takvim1MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbl_takvim1);

        cmb_subelistesi1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cmb_subelistesi1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_subelistesi1İtemStateChanged(evt);
            }
        });
        cmb_subelistesi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_subelistesi1MouseClicked(evt);
            }
        });
        cmb_subelistesi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_subelistesi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_dersProgramıLayout = new javax.swing.GroupLayout(frame_dersProgramı.getContentPane());
        frame_dersProgramı.getContentPane().setLayout(frame_dersProgramıLayout);
        frame_dersProgramıLayout.setHorizontalGroup(
            frame_dersProgramıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_dersProgramıLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frame_dersProgramıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_dersProgramıLayout.createSequentialGroup()
                        .addGroup(frame_dersProgramıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frame_dersProgramıLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(10, 10, 10)
                                .addComponent(cmb_subelistesi1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 232, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        frame_dersProgramıLayout.setVerticalGroup(
            frame_dersProgramıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_dersProgramıLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_dersProgramıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_subelistesi1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel37))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anasayfa");
        setLocation(new java.awt.Point(0, 0));

        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setText("Yeni Öğrenci Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Bir Lisan Bir İnsan Dil Kursu :");

        lbl_subeAdi1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_subeAdi1.setText("sube adı");

        jButton2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton2.setText("Ödeme Al");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton3.setText("Şube Ders Programları");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_subeAdi1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_subeAdi1))
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_taksit1.setVisible(false);
        txt_taksit2.setVisible(false);
        txt_taksit3.setVisible(false);
        txt_taksit4.setVisible(false);
        lbl_taksit1.setVisible(false);
        lbl_taksit2.setVisible(false);
        lbl_taksit3.setVisible(false);
        lbl_taksit4.setVisible(false);
        txt_taksit1.setText("0");
        txt_taksit2.setText("0");
        txt_taksit3.setText("0");
        txt_taksit4.setText("0");
        jLabel40.setVisible(false);
        jLabel41.setVisible(false);
        jLabel42.setVisible(false);
        jLabel43.setVisible(false);
        lbl_taksit5.setText("Toplam Tutar  :");
        dtm.setRowCount(0);
        dtm.setColumnIdentifiers(new String[]{"Ders Saati", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"});
        dtm.addRow(new String[]{"09:00 - 10:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"10:00 - 11:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"11:00 - 12:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"12:00 - 13:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"13:00 - 14:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"14:00 - 15:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"15:00 - 16:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"16:00 - 17:00", " ", " ", " ", " ", " "});

        cmb_subelistesi.removeAllItems();
        cmb_derslist.removeAllItems();
        sube = Database.subeDon();
        for (Sube s : sube) {
            cmb_subelistesi.addItem(s);
        }
        kurs = Database.kursDon();
        for (Kurs k : kurs) {
            cmb_derslist.addItem(k);
        }
        frame_ogrenciKaydet.setTitle("Yeni Öğrenci Kaydet");
        frame_ogrenciKaydet.setSize(1300, 676);
        frame_ogrenciKaydet.setLocationRelativeTo(null);
        frame_ogrenciKaydet.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        cmb_ogrenciList.removeAllItems();
        ogrenci = Database.ogrenciDon();
        for (Ogrenci o : ogrenci) {
            cmb_ogrenciList.addItem(o);
        }
        frame_odemeAl.setTitle("Ödeme Al");
        frame_odemeAl.setSize(430, 250);
        frame_odemeAl.setLocationRelativeTo(null);
        frame_odemeAl.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        dtm.setColumnIdentifiers(new String[]{"Ders Saati", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"});
        dtm.addRow(new String[]{"09:00 - 10:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"10:00 - 11:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"11:00 - 12:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"12:00 - 13:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"13:00 - 14:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"14:00 - 15:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"15:00 - 16:00", " ", " ", " ", " ", " "});
        dtm.addRow(new String[]{"16:00 - 17:00", " ", " ", " ", " ", " "});

        cmb_subelistesi1.removeAllItems();
        sube = Database.subeDon();
        for (Sube s : sube) {
            cmb_subelistesi1.addItem(s);
        }

        frame_dersProgramı.setTitle("Ders Programı");
        frame_dersProgramı.setSize(1300, 530);
        frame_dersProgramı.setLocationRelativeTo(null);
        frame_dersProgramı.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    acilanKurslar tempKurs;
    private void tbl_takvimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_takvimMouseClicked
        // TODO add your handling code here:
        int row = tbl_takvim.getSelectedRow();
        int column = tbl_takvim.getSelectedColumn();
        if (!dtm.getValueAt(row, column).equals(" ")) {
            String odemeTuru;
            if (((String) cmb_odemeTipi.getSelectedItem()).equals("Peşin")) {
                odemeTuru = "pesin_fiyat";
            } else {
                odemeTuru = "taksitli_fiyat";
            }

            tempKurs = ((acilanKurslar) dtm.getValueAt(row, column));
            StringBuilder sql = new StringBuilder();
            sql.append("SELECT   \"public\".\"fiyatlistesi\".\"" + odemeTuru + "\"\n");
            sql.append("FROM     \"public\".\"acilanKurslar\"\n");
            sql.append("INNER JOIN \"public\".\"kurs\"  ON \"public\".\"acilanKurslar\".\"kurs_id\" = \"public\".\"kurs\".\"id\"\n");
            sql.append("INNER JOIN \"public\".\"fiyatlistesi\"  ON \"public\".\"fiyatlistesi\".\"id\" = \"public\".\"kurs\".\"id\"\n");
            sql.append("WHERE \"acilanKurslar\".\"id\" = " + tempKurs.id);
            int i = 0;
            try (Connection con = DriverManager.getConnection(db_adres, db_users, db_pass);
                    Statement s = con.createStatement();
                    ResultSet rs = s.executeQuery(sql.toString())) {
                while (rs.next()) {
                    i = rs.getInt(odemeTuru);
                }
                StringBuilder t = new StringBuilder();
                t.append(i);
                t.append(" Türk Lirası...");
                lbl_tutar.setText(t.toString());

            } catch (Exception e) {
            }
            if (odemeTuru.equals("pesin_fiyat")) {
                txt_taksit5.setText(String.valueOf(i));

            } else {
                int tempi = i / 5;
                txt_taksit1.setText(String.valueOf(tempi));
                txt_taksit2.setText(String.valueOf(tempi));
                txt_taksit3.setText(String.valueOf(tempi));
                txt_taksit4.setText(String.valueOf(tempi));
                txt_taksit5.setText(String.valueOf(tempi));
            }
        }
    }//GEN-LAST:event_tbl_takvimMouseClicked

    private void cmb_subelistesiİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_subelistesiİtemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            Sube tempSube = (Sube) cmb_subelistesi.getSelectedItem();
            txt_subeNot.setText("Adres:\n" + tempSube.sube_adres.trim() + "\n\nUlaşım:\n" + tempSube.sube_ulasim.trim());
            dtm.setRowCount(0);
            dtm.setColumnIdentifiers(new String[]{"Ders Saati", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"});
            dtm.addRow(new String[]{"09:00 - 10:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"10:00 - 11:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"11:00 - 12:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"12:00 - 13:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"13:00 - 14:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"14:00 - 15:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"15:00 - 16:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"16:00 - 17:00", " ", " ", " ", " ", " "});
            ArrayList<acilanKurslar> acilanKurslar = Database.acilanKursDon(tempSube.id);
            for (acilanKurslar a : acilanKurslar) {
                dtm.setValueAt(a, a.ders_saati, a.ders_gunu);
            }
            tbl_takvim.setModel(dtm);
            tbl_takvim.setAutoResizeMode(tbl_takvim.AUTO_RESIZE_OFF);
            tbl_takvim.getColumnModel().getColumn(0).setPreferredWidth(90);
            tbl_takvim.getColumnModel().getColumn(1).setPreferredWidth(235);
            tbl_takvim.getColumnModel().getColumn(2).setPreferredWidth(235);
            tbl_takvim.getColumnModel().getColumn(3).setPreferredWidth(235);
            tbl_takvim.getColumnModel().getColumn(4).setPreferredWidth(235);
            tbl_takvim.getColumnModel().getColumn(5).setPreferredWidth(235);

        }
    }//GEN-LAST:event_cmb_subelistesiİtemStateChanged

    private void cmb_subelistesiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_subelistesiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_subelistesiMouseClicked

    private void cmb_subelistesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_subelistesiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_subelistesiActionPerformed

    private void cmb_odemeTipiİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_odemeTipiİtemStateChanged
        // TODO add your handling code here:
        if (cmb_odemeTipi.getSelectedItem().equals("Peşin")) {
            txt_taksit1.setVisible(false);
            txt_taksit2.setVisible(false);
            txt_taksit3.setVisible(false);
            txt_taksit4.setVisible(false);
            lbl_taksit1.setVisible(false);
            lbl_taksit2.setVisible(false);
            lbl_taksit3.setVisible(false);
            lbl_taksit4.setVisible(false);
            txt_taksit1.setText("0");
            txt_taksit2.setText("0");
            txt_taksit3.setText("0");
            txt_taksit4.setText("0");
            jLabel40.setVisible(false);
            jLabel41.setVisible(false);
            jLabel42.setVisible(false);
            jLabel43.setVisible(false);
            lbl_taksit5.setText("Toplam Tutar  :");
        } else {
            txt_taksit1.setVisible(true);
            txt_taksit2.setVisible(true);
            txt_taksit3.setVisible(true);
            txt_taksit4.setVisible(true);
            lbl_taksit1.setVisible(true);
            lbl_taksit2.setVisible(true);
            lbl_taksit3.setVisible(true);
            lbl_taksit4.setVisible(true);
            jLabel40.setVisible(true);
            jLabel41.setVisible(true);
            jLabel42.setVisible(true);
            jLabel43.setVisible(true);
            lbl_taksit5.setText("Taksit 5      :");

        }
    }//GEN-LAST:event_cmb_odemeTipiİtemStateChanged

    private void cmb_odemeTipiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_odemeTipiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_odemeTipiMouseClicked

    private void cmb_odemeTipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_odemeTipiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_odemeTipiActionPerformed

    private void cmb_derslistİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_derslistİtemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Kurs tempKurs = (Kurs) cmb_derslist.getSelectedItem();
            Sube tempSube = (Sube) cmb_subelistesi.getSelectedItem();
            dtm.setRowCount(0);
            dtm.setColumnIdentifiers(new String[]{"Ders Saati", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"});
            dtm.addRow(new String[]{"09:00 - 10:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"10:00 - 11:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"11:00 - 12:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"12:00 - 13:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"13:00 - 14:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"14:00 - 15:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"15:00 - 16:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"16:00 - 17:00", " ", " ", " ", " ", " "});
            ArrayList<acilanKurslar> acilanKurslar = Database.acilanKursDersdenDon(tempKurs.id, tempSube.id);
            for (acilanKurslar a : acilanKurslar) {
                dtm.setValueAt(a, a.ders_saati, a.ders_gunu);
            }
            tbl_takvim.setModel(dtm);
            tbl_takvim.setAutoResizeMode(tbl_takvim.AUTO_RESIZE_OFF);
            tbl_takvim.getColumnModel().getColumn(0).setPreferredWidth(90);
            tbl_takvim.getColumnModel().getColumn(1).setPreferredWidth(235);
            tbl_takvim.getColumnModel().getColumn(2).setPreferredWidth(235);
            tbl_takvim.getColumnModel().getColumn(3).setPreferredWidth(235);
            tbl_takvim.getColumnModel().getColumn(4).setPreferredWidth(235);
            tbl_takvim.getColumnModel().getColumn(5).setPreferredWidth(235);
        }

    }//GEN-LAST:event_cmb_derslistİtemStateChanged

    private void cmb_derslistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_derslistMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_cmb_derslistMouseClicked

    private void cmb_derslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_derslistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_derslistActionPerformed

    private void txt_taksit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_taksit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_taksit2ActionPerformed

    private void btn_odeKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_odeKaydetActionPerformed
        // TODO add your handling code here:
        StringBuilder sql = new StringBuilder();
        StringBuilder sql2 = new StringBuilder();
        sql.append("INSERT INTO \"public\".\"muhasebe\" ( \"taksit_1\", \"taksit_2\", \"taksit_3\", \"taksit_4\", \"taksit_5\")\n");
        sql.append("VALUES ( " + txt_taksit1.getText() + " , " + txt_taksit2.getText() + " , ");
        sql.append(txt_taksit3.getText() + " , " + txt_taksit4.getText() + " , " + txt_taksit5.getText() + " );");
        sql2.append("INSERT INTO \"public\".\"ogrenci\" ( \"kurs_id\", \"adi\", \"soyadi\", \"odeme_tipi\")\n");
        sql2.append("VALUES ( " + tempKurs.kurs_id + " ,'" + txt_isim.getText() + "' ,'" + txt_soyisim.getText() + "' ,'" + cmb_odemeTipi.getSelectedItem().toString() + "' );");
        try (Connection con = DriverManager.getConnection(db_adres, db_users, db_pass);
                Statement s = con.createStatement()) {
            s.execute(sql.toString());
            s.execute(sql2.toString());
            frame_ogrenciKaydet.dispose();
        } catch (Exception e) {
            System.out.println("Bağlanamadım");
        }
    }//GEN-LAST:event_btn_odeKaydetActionPerformed

    private void txt_soyisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soyisimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soyisimActionPerformed
    Ogrenci tempOgrenci;
    private void cmb_ogrenciListİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ogrenciListİtemStateChanged
        // TODO add your handling code here:

        tempOgrenci = (Ogrenci) cmb_ogrenciList.getSelectedItem();
        StringBuilder sql = new StringBuilder();
        sql.append("SELECT   \"public\".\"ogrenci\".\"adi\",\n");
        sql.append("\"public\".\"ogrenci\".\"soyadi\",\n");
        sql.append("\"public\".\"muhasebe\".\"taksit_1\",\n");
        sql.append("\"public\".\"muhasebe\".\"taksit_2\",\n");
        sql.append("\"public\".\"muhasebe\".\"taksit_3\",\n");
        sql.append("\"public\".\"muhasebe\".\"taksit_4\",\n");
        sql.append("\"public\".\"muhasebe\".\"taksit_5\",\n");
        sql.append("\"public\".\"muhasebe\".\"id\"\n");
        sql.append("FROM     \"public\".\"ogrenci\"\n");
        sql.append("INNER JOIN \"public\".\"muhasebe\"  ON \"public\".\"ogrenci\".\"id\" = \"public\".\"muhasebe\".\"id\"\n");
        sql.append("where ogrenci.id = ");

        sql.append(tempOgrenci.id);
        try (Connection con = DriverManager.getConnection(db_adres, db_users, db_pass);
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery(sql.toString())) {
            while (rs.next()) {
                if (rs.getInt("taksit_1") == 0) {
                    lbl_t1.setText(String.valueOf(rs.getInt("taksit_1")));
                    lbl_t1.setForeground(Color.red);
                } else {
                    lbl_t1.setText(String.valueOf(rs.getInt("taksit_1")));
                    lbl_t1.setForeground(Color.BLACK);
                }
                if (rs.getInt("taksit_2") == 0) {
                    lbl_t2.setText(String.valueOf(rs.getInt("taksit_2")));
                    lbl_t2.setForeground(Color.red);
                } else {
                    lbl_t2.setText(String.valueOf(rs.getInt("taksit_2")));
                    lbl_t2.setForeground(Color.black);
                }
                if (rs.getInt("taksit_3") == 0) {
                    lbl_t3.setText(String.valueOf(rs.getInt("taksit_3")));
                    lbl_t3.setForeground(Color.red);
                } else {
                    lbl_t3.setText(String.valueOf(rs.getInt("taksit_3")));
                    lbl_t3.setForeground(Color.black);
                }
                if (rs.getInt("taksit_4") == 0) {
                    lbl_t4.setText(String.valueOf(rs.getInt("taksit_4")));
                    lbl_t4.setForeground(Color.red);
                } else {
                    lbl_t4.setText(String.valueOf(rs.getInt("taksit_4")));
                    lbl_t4.setForeground(Color.black);
                }
                if (rs.getInt("taksit_5") == 0) {
                    lbl_t5.setText(String.valueOf(rs.getInt("taksit_5")));
                    lbl_t5.setForeground(Color.red);
                } else {
                    lbl_t5.setText(String.valueOf(rs.getInt("taksit_5")));
                    lbl_t5.setForeground(Color.black);
                }

            }
        } catch (SQLException e) {
            System.out.println("Bağlanamadim");
        }
    }//GEN-LAST:event_cmb_ogrenciListİtemStateChanged

    private void cmb_ogrenciListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_ogrenciListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ogrenciListMouseClicked

    private void cmb_ogrenciListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ogrenciListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ogrenciListActionPerformed

    private void btn_odeKaydet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_odeKaydet1ActionPerformed
        // TODO add your handling code here:
        ArrayList<JLabel> lbl = new ArrayList<>();
        lbl.add(lbl_t1);
        lbl.add(lbl_t2);
        lbl.add(lbl_t3);
        lbl.add(lbl_t4);
        lbl.add(lbl_t5);

        for (int i = 0; i < lbl.size(); i++) {
            int k = i + 1;
            if (Integer.valueOf(lbl.get(i).getText()) == 0) {
                int c = Integer.valueOf(lbl.get(i - 1).getText());
                try (Connection con = DriverManager.getConnection(db_adres, db_users, db_pass);
                        Statement s = con.createStatement()) {
                    StringBuilder sql = new StringBuilder();
                    sql.append("UPDATE \"public\".\"muhasebe\" SET\n");
                    sql.append("\"taksit_" + k + "\" = ");
                    sql.append(c + "\n");
                    sql.append("where  \"id\" = " + tempOgrenci.id);
                    s.execute(sql.toString());
                    lbl.get(i).setText(String.valueOf(c));
                    lbl.get(i).setForeground(Color.black);

                } catch (Exception e) {
                }

                break;
            }
        }
    }//GEN-LAST:event_btn_odeKaydet1ActionPerformed

    private void frame_odemeAlWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frame_odemeAlWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_frame_odemeAlWindowDeactivated

    private void tbl_takvim1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_takvim1MouseClicked

    }//GEN-LAST:event_tbl_takvim1MouseClicked

    private void cmb_subelistesi1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_subelistesi1İtemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            Sube tempSube = (Sube) cmb_subelistesi1.getSelectedItem();
            dtm.setRowCount(0);
            dtm.setColumnIdentifiers(new String[]{"Ders Saati", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"});
            dtm.addRow(new String[]{"09:00 - 10:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"10:00 - 11:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"11:00 - 12:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"12:00 - 13:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"13:00 - 14:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"14:00 - 15:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"15:00 - 16:00", " ", " ", " ", " ", " "});
            dtm.addRow(new String[]{"16:00 - 17:00", " ", " ", " ", " ", " "});
            acilanKurslar = Database.acilanKursDon(tempSube.id);
            for (acilanKurslar a : acilanKurslar) {
                dtm.setValueAt(a, a.ders_saati, a.ders_gunu);
            }
            tbl_takvim1.setModel(dtm);
            tbl_takvim1.setAutoResizeMode(tbl_takvim1.AUTO_RESIZE_OFF);
            tbl_takvim1.getColumnModel().getColumn(0).setPreferredWidth(90);
            tbl_takvim1.getColumnModel().getColumn(1).setPreferredWidth(235);
            tbl_takvim1.getColumnModel().getColumn(2).setPreferredWidth(235);
            tbl_takvim1.getColumnModel().getColumn(3).setPreferredWidth(235);
            tbl_takvim1.getColumnModel().getColumn(4).setPreferredWidth(235);
            tbl_takvim1.getColumnModel().getColumn(5).setPreferredWidth(235);

        }
    }//GEN-LAST:event_cmb_subelistesi1İtemStateChanged

    private void cmb_subelistesi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_subelistesi1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_subelistesi1MouseClicked

    private void cmb_subelistesi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_subelistesi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_subelistesi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anasayfa().setVisible(true);
            }
        });
    }
    private static final String db_adres = "jdbc:postgresql://localhost:5432/DilKursu";
    private static final String db_users = "postgres";
    private static final String db_pass = "admin";
    String subeadi;
    DefaultTableModel dtm = new DefaultTableModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_odeKaydet;
    private javax.swing.JButton btn_odeKaydet1;
    private javax.swing.JComboBox<Kurs> cmb_derslist;
    private javax.swing.JComboBox<String> cmb_odemeTipi;
    private javax.swing.JComboBox<Ogrenci> cmb_ogrenciList;
    private javax.swing.JComboBox<Sube> cmb_subelistesi;
    private javax.swing.JComboBox<Sube> cmb_subelistesi1;
    private javax.swing.JFrame frame_dersProgramı;
    private javax.swing.JDialog frame_odemeAl;
    private javax.swing.JFrame frame_ogrenciKaydet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbl_subeAdi1;
    private javax.swing.JLabel lbl_t1;
    private javax.swing.JLabel lbl_t2;
    private javax.swing.JLabel lbl_t3;
    private javax.swing.JLabel lbl_t4;
    private javax.swing.JLabel lbl_t5;
    private javax.swing.JLabel lbl_taksit1;
    private javax.swing.JLabel lbl_taksit2;
    private javax.swing.JLabel lbl_taksit3;
    private javax.swing.JLabel lbl_taksit4;
    private javax.swing.JLabel lbl_taksit5;
    private javax.swing.JLabel lbl_tutar;
    private javax.swing.JTable tbl_takvim;
    private javax.swing.JTable tbl_takvim1;
    private javax.swing.JTextField txt_isim;
    private javax.swing.JTextField txt_soyisim;
    private javax.swing.JTextArea txt_subeNot;
    private javax.swing.JTextField txt_taksit1;
    private javax.swing.JTextField txt_taksit2;
    private javax.swing.JTextField txt_taksit3;
    private javax.swing.JTextField txt_taksit4;
    private javax.swing.JTextField txt_taksit5;
    // End of variables declaration//GEN-END:variables
}
